### ISSUE TITLE
New error after kitty upgrade, cannot import name 'key_func'

### ISSUE THREAD

**Issue by SijanC147** [yurikhan/kitty_grab#17]
Still not sure if it's directly related to the update, need to look into it some more, but thought i'd leave this here for your information, and just in case you have any advice re: dealing with it. LOVE this plugin btw, keep up the awesome work! 

<img width="1649" alt="CleanShot 2022-01-07 at 13 24 56@2x" src="https://user-images.githubusercontent.com/13831460/148543950-be470449-f928-4765-b67a-c67c01451cfa.png">

**Comment by yurikhan** [comment]
This looks very similar to what #16 was supposed to fix. Are you on the latest version of kitty_grab which pushed just yesterday?

(Also, for your future bug reports, please prefer copying text from terminal and embedding it as a code block, rather than screenshotting. Rationale: People will be able to find your bug report by error message text.)

**Comment by SijanC147** [comment]
Sorry I missed that, that was it, upgraded and all is good. thanks!

(cheers for the tip on screenshots btw, didn't cross my mind)
